### ISSUE TITLE
Create a link to Threshold's brand assets

### ISSUE THREAD

**Issue by Luna5-threshold** [threshold-network/website#81]
Threshold Network's brand assets currently reside in our Notion, however, we need to provide a link to them in our official page. 

Please include a link to our brand assets within our website -> [https://www.notion.so/thresholdnetwork/06ca766fc2cd402ab99bfe952a41c5af?v=a2e40d1427d54cfd8c48ea0c9ab9e7dd&pvs=4](https://www.notion.so/thresholdnetwork/06ca766fc2cd402ab99bfe952a41c5af?v=a2e40d1427d54cfd8c48ea0c9ab9e7dd&pvs=4)

**Comment by liz-shinn** [comment]
@r-czajkowski & @michalsmiarowski 

We have a design for this that adds a page to the website Brand Assets. On this page, there is downloadable assets & design documentation on the Threshold website. I will create a ticket for it. 

Since we likely won't have bandwidth to tackle those designs this sprint, in the meantime let's add a link like Luna requests above.

Here's the design adding the "Brand Assets" external link:
https://thresholdnetwork.notion.site/06ca766fc2cd402ab99bfe952a41c5af

DESKTOP:
<img width="424" alt="Screenshot 2023-05-04 at 1 28 18 PM" src="https://user-images.githubusercontent.com/57226633/236282408-01c8741b-70f3-435c-8ed6-24be9a839130.png">

MOBILE:
<img width="830" alt="Screenshot 2023-05-04 at 1 27 40 PM" src="https://user-images.githubusercontent.com/57226633/236282467-200feace-034c-459e-91f5-b1750378656d.png">
